### ISSUE TITLE
config.js:19 throw new Error(`The "${name} environment variable must be set

### ISSUE THREAD

**Issue by Raja-web-developer** [smart-on-fhir/smart-launcher#76]
Hi 
How to fix the issue.

Error: The "FHIR_SERVER_R2 environment variable must be set
    at D:\smart-appone\smart-launcher\src\config.js:19:11
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (D:\smart-appone\smart-launcher\src\config.js:17:3)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (D:\smart-appone\smart-launcher\src\index.js:4:20)
![image](https://user-images.githubusercontent.com/114417265/194061528-01a0bf5f-fd89-4bc1-8615-5be0858ff85e.png)

**Comment by Mekhadev2025** [comment]
Hey @Raja-web-developer , I ran into the same issue and here’s how I fixed it 
## ✅ Steps to Fix:

### 1. Install `dotenv`

```bash
npm install dotenv
```

### 2. Create a .env file
In the root of your project, add the required environment variables:

```bash
FHIR_SERVER_R2=https://r2.smarthealthit.org
FHIR_SERVER_R3=https://r3.smarthealthit.org
FHIR_SERVER_R4=https://r4.smarthealthit.org
PICKER_CONFIG_R2=r2
PICKER_CONFIG_R3=r3
PICKER_CONFIG_R4=r4
```
### 3.  Add dotenv to index.js
 Add the following line at the top of your index.js, before const express = require("express"):

```bash
require("dotenv").config();
```

![Image](https://github.com/user-attachments/assets/8656a1fa-7dde-4034-9ae9-1cf71c4dc8f7)
